parameters:
  project: ''
  module: ''
  name: ''

jobs:

  - job: ${{ parameters.name }}_Build
    displayName: ${{ parameters.mame }}
    pool:
      vmImage: 'macos-latest'
    variables:
      - group: AgoraKeys
    steps:
      - script: cd ${{ parameters.project }} && ls && python ci.env.py && echo $(agora.appId)
        env:
          AGORA_APP_ID: $(agora.appId)

      - task: Gradle@2
        inputs:
          workingDirectory: ${{ parameters.project }}/${{ parameters.module }}
          gradleWrapperFile: ${{ parameters.project }}/gradlew
          options: '--stacktrace'
          gradleOptions: '-Xmx3072m'
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'assembleDebug'

      - task: CopyFiles@2
        inputs:
          Contents: '**/*.apk'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - script: cd $(Build.ArtifactStagingDirectory) && zip -r ${{ parameters.name }}.zip .

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/${{ parameters.name }}.zip'
          ArtifactName: ${{ parameters.name }}
